"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "./services/store/store";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import axios from "axios";
import Header from "./components/ui/header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const queryClient = new QueryClient();
axios.defaults.baseURL = process.env.BASE_URL;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider store={store}>
        <QueryClientProvider client={queryClient}>
          <body
            className={`font-inter antialiased bg-white text-gray-900 tracking-tight`}
          >
            <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
              <Header />
              {children}
            </div>
          </body>{" "}
        </QueryClientProvider>
      </Provider>
    </html>
  );
}
